### PR TITLE
151042 main keys generation

### PR DESCRIPTION
**Pull request by vananyev**

### CODE REVIEW

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by vananyev** [comment]
This is PR of first (of 3) part of authentication and permission task. Please take a look

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Pull request closed without merging**
