### PR TITLE
child node, conf and attr removing fix

### PR DESCRIPTION
**Pull request by dmitriyisaev**
- child node removing bug fix
- attributes and config remove instead of drop to initial value
- refactoring

### CODE REVIEW

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Comment by eduardyuzlikeev** [comment]
:+1:

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Pull request merged**
