### PR TITLE
Kryo serialization fix + conf cleanup

### PR DESCRIPTION
**Pull request by ilya-martynov**

### CODE REVIEW

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Review by dmitriyisaev — APPROVED** [review]

**Pull request merged**
