### PR TITLE
Feature/139370

### PR DESCRIPTION
**Pull request by dmitriyisaev**

### CODE REVIEW

**Comment by ilya-martynov** [comment]
LGTM
However, could we wait for Ilya Dubovsky (SPb team DevOps) review on this ?
I suppose it is good point to involve him into the process.
What do you think guys ?

**Comment by uralian** [comment]
Looks good to me.

**Comment by ilya-dubovskiy** [comment]
lgtm
thanks for waiting for me

**Comment by ilya-martynov** [comment]
Merged.

**Pull request merged**
