### PR TITLE
workaround for https://github.com/akka/akka/issues/24934

### PR DESCRIPTION
**Pull request by dmitriyisaev**

### CODE REVIEW

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Review by vananyev — APPROVED** [review]

**Pull request merged**
