### PR TITLE
Fix/155325 upstream connection issue

### PR DESCRIPTION
**Pull request by dmitriyisaev**

### CODE REVIEW

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Review by ilya-martynov — APPROVED** [review]
Looks well to me.

**Comment by ilya-martynov** [comment]
Please, resolve conf conflicts carefully :)

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Do not merge!!

**Comment by ilya-dubovskiy** [comment]
Build and tests are GOOD

**Pull request merged**
